# Generated by Django 4.0.3 on 2024-02-01 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binvo',
            name='name',
        ),
    ]
